<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>UniversalBatteryOverlay</AssemblyName>
    <RootNamespace>UniversalBatteryOverlay</RootNamespace>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <Version>0.34.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="app.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
